test_project/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

test_project/flashcard/urls.py
from django.urls import path
from .views import cards_of_a_deck_view, deck_add_form_view, deck_add_view, deck_delete_view, DeckListView, DeckDetailView , CardListView, CardDetailView, CardCreateView, CardUpdateView, CardDeleteView

urlpatterns = [
    path('', DeckListView.as_view(), name='home'),
    #------------------- htmx post request ------------------------------------
    path('decks/<int:deck_id>/', cards_of_a_deck_view, name='deck_detail'), 
    path('deck_form/', deck_add_form_view, name='deck_add_form' ),
    path('deck_add/', deck_add_view, name='deck_add' ),
    path("decks/<int:deck_id>/delete/", deck_delete_view, name="deck_delete"),

    path('add/', CardCreateView.as_view(), name='add_card'),
    path('<int:pk>/', CardDetailView.as_view(), name='card_detail'),
    path('<int:pk>/delete/', CardDeleteView.as_view(), name='delete_card'),
    path('<int:pk>/edit/', CardUpdateView.as_view(), name='edit_card'),

]

test_project/test_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flashcard.urls')),

]

test_project/core/models.py
from django.db import models

# Create your models here.

test_project/flashcard/models.py
from django.db import models

# Create your models here.

class Card(models.Model):
    question = models.CharField(max_length=100)
    answer = models.TextField()
    def __str__(self):
        return self.question
    def get_absolute_url(self):
        return reverse('card_detail', args=[str(self.id)])


class Deck(models.Model):
    name = models.CharField(max_length=100)
    cards = models.ManyToManyField(Card)
    def __str__(self):
        return self.name    
    
    

test_project/flashcard/forms.py
from django import forms
from .models import Deck, Card

test_project/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return HttpResponse("<h1>Welcome to Django!</h1><p>Your Django application is running successfully.</p>")

test_project/flashcard/views.py
import json, struct
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
from .models import Card, Deck


def cards_of_a_deck_view(request, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    cards = deck.cards.all()
    return render(request, 'flashcard/deck_detail.html', {'deck': deck, 'cards': cards})


def deck_add_form_view(request):
    if request.method == 'POST':
        deck_id = request.POST.get('deck_id')
        deck = get_object_or_404(Deck, pk=deck_id)
        context = {'deck': deck}
        return render(request, 'flashcard/partials/deck_form.html', context=context)

    return render(request, 'flashcard/partials/deck_form.html')

@require_POST
def deck_add_view(request):
    name = request.POST.get('name')
    deck_id = request.POST.get('deck_id')
    print(deck_id)
    if deck_id: 
    # update deck name    
        deck = get_object_or_404(Deck, pk=deck_id)
        deck.name = name
        deck.save()
        return render(request, 'flashcard/includes/deck_item.html', {'deck': deck})
    
    # create new deck
    deck = Deck.objects.create(name=name)
    return render(request, 'flashcard/partials/deck_add_button_item.html', {'deck': deck})


def deck_delete_view(request, deck_id):
    deck = get_object_or_404(Deck, pk=deck_id)
    deck.delete()
    return HttpResponse('')

class DeckListView(ListView):
    model = Deck
    template_name = 'flashcard/index.html'
    context_object_name = 'decks'




class DeckDetailView(DetailView):
    model = Deck
    template_name = 'flashcard/deck_detail.html'
    context_object_name = 'deck'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        
        return render(request, self.template_name, self.get_context_data(object=self.object))


class CardListView(ListView):
    model = Card
    template_name = 'flashcard/card_list.html'
    context_object_name = 'cards'

class CardDetailView(DetailView):
    model = Card
    template_name = 'flashcard/card_detail.html'
    context_object_name = 'card'

class CardDeleteView(DeleteView):
    model = Card
    template_name = "flashcard/card_confirm_delete.html"
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return 


class CardCreateView(CreateView):
    model = Card
    template_name = 'flashcard/card_form.html'
    fields = ['question', 'answer']
    success_url = reverse_lazy('card_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view_type"] = "create"
        return context
    
    
class CardUpdateView(UpdateView):
    model = Card    # Specify the model to use
    template_name = 'flashcard/card_form.html'  # Specify the template to use
    fields = ['question', 'answer']  # Specify the fields to include in the form
    success_url = reverse_lazy('card_list')  # Specify the URL to redirect to after successful form submission  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view_type"] = "update" 
        return context
    

test_project/flashcard/templates/flashcard/_base.html
{% load django_htmx %}
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>
        {% block title %} {% endblock title %}
    </title>
    {% htmx_script %}

    <style>
      svg{
        display: inline;
      }
    </style>  

  </head>
  <body hx-headers='{"x-csrftoken": "{{ csrf_token }}"}'>
    {% block content %} {% endblock content %}

    
  </body>
</html>

test_project/flashcard/templates/flashcard/card_confirm_delete.html
{% extends 'flashcard/_base.html' %}

{% block title %}
confirm delete card
{% endblock title %}

{% block content %}

<h1>Confirm Delete</h1>
<p>Are you sure you want to delete this card"{{ card.question }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
</form>
<a href="{% url 'card_list' %}">Cancel</a>

{% endblock %}

test_project/flashcard/templates/flashcard/card_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Card ID: {{ card.id }}</h3>
    
    <ul>
        <li>
           <p> <strong> Question: </strong> {{ card.question }} </p>
           <p><strong> answer: </strong> {{ card.answer }} </p>
        </li>
    </ul>
 
   

    
</body>
</html>

test_project/flashcard/templates/flashcard/card_form.html
 {% extends 'flashcard/_base.html' %}

 {% block title %}
 Add Card
 {% endblock title %}
 
 {% block content %}
 
 <div class="w-full max-w-xs">
    <h1>
      {% if view_type == 'create' %}
            Add
          {% else %}
            Update
          {% endif %}
      Card</h1>
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
     {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="id_question">
          Question
        </label>
        <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="id_question" name="question" type="text" value="{{ form.question.value|default:'' }}">
      </div>
      <div class="mb-6">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="id_answer">
          Answer
        </label>
        <input class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="id_answer" name="answer" type="text" value="{{ form.answer.value|default:'' }}">
        
      </div>
      
      <div class="flex items-center justify-between">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
          {% if view_type == 'create' %}
            Add
          {% else %}
            Update
          {% endif %}
        </button>
        <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="{% url 'card_list'  %}">
          Cancel
        </a>
      </div>
    </form>
</div>

 {% endblock %}

test_project/flashcard/templates/flashcard/card_list.html
    <div class="bg-white p-8 overflow-auto mt-16 h-screen">
        <h2 class="text-2xl mb-4">Cards</h2>
      
        <!-- Classes Table -->
        <div class="relative overflow-auto">
          <div class="overflow-x-auto rounded-lg">
            <table class="min-w-full bg-white border mb-20">
              <thead>
                <tr class="bg-[#2B4DC994] text-center text-xs md:text-sm font-thin text-white">
                  <th class="p-0">
                    <span class="block py-2 px-3 border-r border-gray-300">ID</span>
                  </th>
                  <th class="p-0">
                    <span class="block py-2 px-3 border-r border-gray-300">Question</span>
                  </th>
                  <th class="p-0">
                    <span class="block py-2 px-3 border-r border-gray-300">Answer</span>
                  </th>
                  <th class="p-4 text-xs md:text-sm">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for card in cards %}
                <tr class="border-b text-xs md:text-sm text-center text-gray-800">
                  <td class="p-2 md:p-4">{{ card.id }}</td>
                  <td class="p-2 md:p-4"> {{ card.question }}</td>
                  <td class="p-2 md:p-4">{{ card.answer }}</td>
                  <td class="relative p-2 md:p-4 flex justify-center space-x-2">
                    <a href="{% url 'edit_card' card.id %}" class="bg-blue-500 text-white px-3 py-1 rounded-md text-xs md:text-sm">Edit</a>
                    <a href="{% url 'delete_card' card.id %}" class="bg-red-500 text-white px-3 py-1 rounded-md text-xs md:text-sm">Delete</button>
                  </td>
                </tr>
               {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

test_project/flashcard/templates/flashcard/deck_detail.html
{% extends 'flashcard/_base.html' %}
{% block content %}

    <h3>Deck :{{ deck.name }}</h3>
    
    {% include 'flashcard/card_list.html' %}
   
 {% endblock %}

test_project/flashcard/templates/flashcard/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Card ID: {{ card.id }}</h3>
    
    <ul>
        <li>
           <p> <strong> Question: </strong> {{ card.question }} </p>
           <p><strong> answer: </strong> {{ card.answer }} </p>
        </li>
    </ul>
 
   

    
</body>
</html>

test_project/flashcard/templates/flashcard/includes/deck_add_button.html
<button hx-get="{% url 'deck_add_form'  %}" hx-swap="outerHTML" class="text-blue-500">
    <div class="bg-white p-4 text-center rounded-lg shadow-md w-64 hover:bg-gray-200">
        <div class=" text-center">

            <svg class="mx-auto" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" id="IconChangeColor" height="3.6rem" width="3.6rem"><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z" id="mainIconPathAttribute" fill="green" stroke-width="0.3" stroke="#ff0000"></path></svg>

        </div>
        <p>Add</p>
    </div>
</button>

test_project/flashcard/templates/flashcard/includes/deck_item.html
<div id="deck-{{ deck.id }}" class="grid grid-cols-1">
    <button hx-post="{% url 'deck_detail' deck.id %}" hx-trigger="click"
        hx-target="#deckList"
        hx-swap="outerHTML" 
        class="text-blue-500">
            <div class="bg-white p-4 text-center rounded-lg shadow-md w-64 hover:bg-gray-200">
                <h3 class="text-xl font-bold mb-2">{{ deck.name }}</h3>
                <p class="text-gray-700 mb-4">{{ deck.cards.count }} cards</p>
            </div>
    </button>
    <div class="grid grid-cols-2 mt-1 w-full">
        <button hx-delete="{% url 'deck_delete' deck.id %}" hx-trigger="click"
            hx-target="#deck-{{ deck.id }}"
            hx-swap="outerHTML" 
            class="text-blue-500">
                <div class="bg-white pb-2 pt-3 text-center rounded-lg shadow-md w-32 hover:bg-gray-200">
                    <p class="text-gray-700 mb-1">Delete ❌</p>
                </div>
        </button>
        <button hx-post="{% url 'deck_add_form'%}" hx-trigger="click"
            hx-target="#deck-{{ deck.id }}"
            hx-swap="outerHTML" 
            class="text-blue-500"
            hx-vals='{"deck_id": "{{ deck.id }}", 
                "deck_name": "{{ deck.name }}"}'
            >
                <div class="bg-white pb-1 pt-3 text-center rounded-lg shadow-md w-32 hover:bg-gray-200">
                    <p class="text-gray-700 mb-1">Edit <svg width='2rem' height='2rem'  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M5 18.89H6.41421L15.7279 9.57627L14.3137 8.16206L5 17.4758V18.89ZM21 20.89H3V16.6473L16.435 3.21231C16.8256 2.82179 17.4587 2.82179 17.8492 3.21231L20.6777 6.04074C21.0682 6.43126 21.0682 7.06443 20.6777 7.45495L9.24264 18.89H21V20.89ZM15.7279 6.74785L17.1421 8.16206L18.5563 6.74785L17.1421 5.33363L15.7279 6.74785Z"></path></svg></p>
                </div>
        </button>

    </div>
</div>

test_project/flashcard/templates/flashcard/index.html
{% extends 'flashcard/_base.html' %}




{% block title %} FlashCard {% endblock title %}

{% block content %}

<div class="flex flex-wrap gap-4 p-6 justify-center text-lg font-serif" id="deckList">
    {% for deck in decks %}

    {% include 'flashcard/includes/deck_item.html' %}

    {% endfor %}

{% include 'flashcard/includes/deck_add_button.html' %}

</div> 

{% endblock %}

test_project/flashcard/templates/flashcard/partials/deck_add_button_item.html
{# deck_add_button.html and deck_item.html combined #}



{% include "flashcard/includes/deck_item.html" %}
{% include "flashcard/includes/deck_add_button.html" %}

test_project/flashcard/templates/flashcard/partials/deck_form.html
<form hx-post="{% url 'deck_add' %}" hx-swap="outerHTML" class="bg-white p-4 rounded-lg shadow-md w-64">
    <div class="mb-4">
        <label for="name" class="block text-gray-700 text-sm font-bold mb-2">Deck Name:</label>
        <input type="text" id="name" name="name" 
        class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
        value="{{ deck.name|default_if_none:'' }}"
        >
        <input type="hidden" name="deck_id" value="{{ deck.id|default_if_none:'' }}">
    </div>
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
    {% if deck.id %}
       Update Deck{% else %}
       Create Deck{% endif %}
    </button>
</form>